services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bootcamp-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=BootcampAPIDB;Username=postgres;Password=admin"


  postgres:
    image: postgres:16
    container_name: bootcamp-postgres
    restart: always
    environment:
      POSTGRES_DB: BootcampAPIDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: